Update patch-playstore

diff --git a/patch-playstore b/patch-playstore
--- a/patch-playstore
+++ b/patch-playstore
@@ -16,6 +16,11 @@ setup () {
 	command -v apksigner >/dev/null || error "apksigner not found"
 	command -v aapt >/dev/null || error "aapt not found"
 
+	# prepare and use android framework to avoid issues with non-translatable resources
+	[ -z "$ANDROIDSDK" ] && ANDROIDSDK=33
+	[ ! -d framework ] && mkdir framework
+	[ ! -f framework/1.apk ] && wget https://github.com/Sable/android-platforms/raw/master/android-${ANDROIDSDK}/android.jar -O framework/1.apk
+
 	gplay_version=$(aapt dump badging "${gplay}" | gawk -F \' '/^package: name/{print $4}')
 	gplay_version_p=$(aapt dump badging "${gplay}" | gawk -F \' '/^package: name/{print $6}' | sed -e 's/\ .*//')
 	gplay_name=$(aapt dump badging "${gplay}" | gawk -F \' '/^package: name/{print $2}')
@@ -39,7 +44,7 @@ setup () {
 unpack_gplay () {
 	echo "[1] Unpacking APK"
 	rm -rf "${gplay_work}" "${gplay_orig}"
-	apktool -q d ${APKTOOL_FLAGS} "${gplay}" -o "${gplay_work}" || error "apktool failed to unpack ${gplay}"
+	apktool -q d ${APKTOOL_FLAGS} -f framework "${gplay}" -o "${gplay_work}" || error "apktool failed to unpack ${gplay}"
 
 	grep -q FAKE_PACKAGE_SIGNATURE "${gplay_work}/AndroidManifest.xml" && error "APK already patched!"
 
@@ -50,7 +55,7 @@ unpack_gplay () {
 repack_gplay () {
 	echo "[3] Repacking APK"
 	diff -Nupr "${gplay_orig}" "${gplay_work}" > "Phonesky-${gplay_version_p}.diff"
-	apktool -q b ${APKTOOL_FLAGS} "${gplay_work}" || error "apktool failed to repack ${gplay}"
+	apktool -q b ${APKTOOL_FLAGS} -f framework "${gplay_work}" || error "apktool failed to repack ${gplay}"
 
 	mv "${gplay_dist}" "${gplay_out}"
 	[ -f "${keystore}" ] && apksigner sign --ks "${keystore}" "${gplay_out}"
@@ -89,6 +94,11 @@ patch_gplay () {
 	public_insert="    <public type=\"string\" name=\"fake_signature\" id=\"0x${public_id_insert}\" />"
 
 	sed "${public_pos_insert}i${public_insert}" -i "${gplay_work}/res/values/public.xml"
+
+	# patch known "no public resource" errors:
+        sed -i 's#@android:color/background_floating_device_default_dark#@*android:color/background_floating_device_default_dark#g' ${gplay_work}/res/color/*.xml
+        sed -i 's#@android:color/GM2_grey_800#@*android:color/GM2_grey_800#g' ${gplay_work}/res/color/*.xml
+        sed -i 's/@android:color/@*android:color/g' ${gplay_work}/res/values/styles.xml
 }
 
 for file in "${@}"; do
