ci: adapt to common release push

diff --git a/.gitea/workflows/build.yml b/.gitea/workflows/build.yml
--- a/.gitea/workflows/build.yml
+++ b/.gitea/workflows/build.yml
@@ -132,7 +132,7 @@ jobs:
       uses: actions/upload-artifact@v3
       id: upla
       with:
-        name: vt-artifacts
+        name: release-artifact
         path: apks/*.apk
 
     - name: Commit & push diff
@@ -158,47 +158,43 @@ jobs:
       repo: ${{ github.repository_owner }}/${{ github.event.repository.name }}
       filepattern: '*.apk'
 
-  release:
+  preprelease:
     needs: [ build, scan ]
     runs-on: docker-node-latest
+    outputs:
+      vtres: ${{ steps.r.outputs.vt_results }}
     steps:
+      - name: Prep release body
+        id: r
+        run: |
+          VTRES="${{ needs.scan.outputs.results }}"
+          if [ -z "$VTRES" ];then echo "ERROR: missing scan results"; exit 3;fi
+          for v in $(echo "$VTRES" | tr ',' ' ' );do
+            a="${v/apk=*}apk"
+            u="${v/*=http}"
+            if [ "$a" == "Phonesky_AXP-OS.apk" ];then s="${{ needs.build.outputs.apk_sha_unsigned }}";fi
+            if [ "$a" == "Phonesky_AXP-OS-signed.apk" ];then s="${{ needs.build.outputs.apk_sha_signed }}";fi
+            RES="$RES**$a**<br/>- sha256: $s<br/>- Virustotal [scan result](http${u})<br/><br/>"
+          done
+          echo "vt_results=$RES" >> $GITHUB_OUTPUT
 
-    - name: Prep release body
-      run: |
-        VTRES="${{ needs.scan.outputs.results }}"
-        if [ -z "$VTRES" ];then echo "ERROR: missing scan results"; exit 3;fi
-        for v in $(echo "$VTRES" | tr ',' ' ' );do
-          a="${v/apk=*}apk"
-          u="${v/*=http}"
-          if [ "$a" == "Phonesky_AXP-OS.apk" ];then s="${{ needs.build.outputs.apk_sha_unsigned }}";fi
-          if [ "$a" == "Phonesky_AXP-OS-signed.apk" ];then s="${{ needs.build.outputs.apk_sha_signed }}";fi
-          RES="$RES**$a**<br/>- sha256: $s<br/>- Virustotal [scan result](http${u})<br/><br/>"
-        done
-        echo "vt_results=$RES" >> $GITHUB_ENV
-
-    - name: Get artifacts from build
-      uses: actions/download-artifact@v2
-      with:
-        name: vt-artifacts
-        merge-multiple: true
-        path: apks
-        #github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
-        #repository:  ${{ inputs.repo }}
-        #run-id: ${{ inputs.wfid }}
-
-    - name: Generate pre-release on MIRROR
-      uses: https://gitea.com/actions/gitea-release-action@v1
-      with:
-        token: "${{ secrets.MIRROR_TOKEN_RW }}"
-        tag_name: "${{ needs.build.outputs.apk_version_short }}_${{ needs.build.outputs.apk_version_code }}"
-        target_commitish: axp
-        prerelease: true
-        server_url: https://${{ vars.MIRROR_ORG_DOMAIN }}
-        repository: ${{ vars.MIRROR_ORG_NAME }}/${{ github.event.repository.name }}
-        name: "UNTESTED: ${{ needs.build.outputs.apk_version_full }}"
-        body: |
+  release-codeberg:
+    name: "Release @Codeberg"
+    uses: https://codeberg.org/AXP-OS/actions/.gitea/workflows/release_mirror_main.yaml@main
+    runs-on: docker-node-latest
+    needs: preprelease
+    secrets: inherit
+    with:
+      workflow_id: ${{ github.run_id }}
+      repo: ${{ github.event.repository.name }} # without org!
+      title: "UNTESTED: ${{ needs.build.outputs.apk_version_full }}"
+      tag: "${{ needs.build.outputs.apk_version_short }}_${{ needs.build.outputs.apk_version_code }}"
+      targetc: axp
+      pre: true
+      #filepattern: '*.apk'
+      body: |
           ## Phonesky
-          ${{ env.vt_results }}
+          ${{ needs.preprelease.outputs.vtres }}
           
           ## Origin source
           - APKMirror [link](https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-${{ needs.build.outputs.apk_version_uri }}-release/)
@@ -206,66 +202,21 @@ jobs:
           ## Diff (unpacked APK vs Release)
           - [Phonesky-${{ needs.build.outputs.apk_version_short }}.diff](https://${{ vars.MIRROR_ORG_DOMAIN }}/${{ vars.MIRROR_ORG_NAME }}/${{ github.event.repository.name }}/src/branch/axp/Phonesky-${{ needs.build.outputs.apk_version_short }}.diff)
 
-          ## Mirror
-          This release is mirrored on: [${{ vars.SCND_MIRROR_ORG_DOMAIN }}](https://${{ vars.SCND_MIRROR_ORG_DOMAIN }}/${{ vars.SCND_MIRROR_ORG_NAME }}/${{ github.event.repository.name }}/releases/${{ needs.build.outputs.apk_version_short }}_${{ needs.build.outputs.apk_version_code }})
-          
-        files: |
-          ${{ github.WORKSPACE }}/apks/Phonesky_AXP-OS.apk
-          ${{ github.WORKSPACE }}/apks/Phonesky_AXP-OS-signed.apk
-
-    - name: Generate pre-release on SECOND MIRROR
-      run: |
-          apt-get update >> /dev/null; apt-get install -y jq curl >> /dev/null
-          json_payload=$(cat <<EOF
-          {
-              "tag_name": "${{ needs.build.outputs.apk_version_short }}_${{ needs.build.outputs.apk_version_code }}",
-              "target_commitish": "axp",
-              "name": "UNTESTED: ${{ needs.build.outputs.apk_version_full }}",
-              "draft": false,
-              "prerelease": true,
-              "generate_release_notes": false,
-              "body": "## Phonesky\n  ${{ env.vt_results }}\n\n  ## Origin source\n  - APKMirror [link](https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-${{ needs.build.outputs.apk_version_uri }}-release/)\n\n  ## Diff (unpacked APK vs Release)\n  - [Phonesky-${{ needs.build.outputs.apk_version_short }}.diff](https://${{ vars.SCND_MIRROR_ORG_DOMAIN }}/${{ vars.SCND_MIRROR_ORG_NAME }}/${{ github.event.repository.name }}/blob/axp/Phonesky-${{ needs.build.outputs.apk_version_short }}.diff)\n\n  ## Mirror\n  This release is mirrored on: [${{ vars.MIRROR_ORG_DOMAIN }}](https://${{ vars.MIRROR_ORG_DOMAIN }}/${{ vars.MIRROR_ORG_NAME }}/${{ github.event.repository.name }}/releases/tag/${{ needs.build.outputs.apk_version_short }}_${{ needs.build.outputs.apk_version_code }})"
-          }
-          EOF
-          )
-
-          RESP=$(curl -sX POST "https://api.${{ vars.SCND_MIRROR_ORG_DOMAIN }}/repos/${{ vars.SCND_MIRROR_ORG_NAME }}/${{ github.event.repository.name }}/releases" \
-            -H 'Content-Type: application/vnd.github+json' \
-            -H "X-GitHub-Api-Version: 2022-11-28" \
-            -H "Authorization: Bearer ${{ secrets.SCND_MIRROR_TOKEN_RW }}" \
-            -w "%{http_code}" \
-            -d "$json_payload")
-
-          #echo -e "\n$RESP\n\n"
-          relid=$(echo "$RESP" | sed '$d' | jq .id || true)
-          status_code=$(echo "$RESP" | jq | tail -n1)
-
-          if [ -z "$status_code" ]||[ "$status_code" != "201" ];then
-            echo "☠️ status_code ERROR $status_code\n\n$RESP"
-            exit 2
-          else
-            echo "🎉 Release created successfully!"
-          fi
-
-          if [ -z "$relid" ];then
-            echo -e "☠️ ERROR, CANNOT GET RELEASE ID\n\n$RESP"
-            exit 3
-          else
-            echo "using release id: $relid"
-            for file in Phonesky_AXP-OS.apk Phonesky_AXP-OS-signed.apk;do
-              URES=$(curl -sX POST "https://uploads.${{ vars.SCND_MIRROR_ORG_DOMAIN }}/repos/${{ vars.SCND_MIRROR_ORG_NAME }}/${{ github.event.repository.name }}/releases/${relid}/assets?name=$file" \
-                -H 'Content-Type: application/vnd.github+json' \
-                -H "X-GitHub-Api-Version: 2022-11-28" \
-                -H "Authorization: Bearer ${{ secrets.SCND_MIRROR_TOKEN_RW }}" \
-                -w "%{http_code}" \
-                --data-binary "@${{ github.WORKSPACE }}/apks/$file")
-              sc_up=$(echo -e "$URES" | jq | tail -n1)
-              if [ "$sc_up" == "201" ];then
-                echo "🎉 uploaded $file successfully!"
-              else
-                echo -e "☠️ ERROR ($sc_up): uploading $file!\n\n$URES"
-                exit 5
-              fi
-            done
-          fi
-          echo "🎉 Release finished successfully!"
+  release-github:
+    name: "Release @Github"
+    uses: https://codeberg.org/AXP-OS/actions/.gitea/workflows/release_mirror_second.yaml@main
+    runs-on: docker-node-latest
+    needs: preprelease
+    secrets: inherit
+    with:
+      workflow_id: ${{ github.run_id }}
+      repo: ${{ github.event.repository.name }} # without org!
+      title: "UNTESTED: ${{ needs.build.outputs.apk_version_full }}"
+      tag: "${{ needs.build.outputs.apk_version_short }}_${{ needs.build.outputs.apk_version_code }}"
+      targetc: axp
+      pre: true
+      #filepattern: '*.apk'
+      body: "## Phonesky\n  ${{ needs.preprelease.outputs.vtres }}\n\n  ## Origin source\n  - APKMirror [link](https://www.apkmirror.com/apk/google-inc/google-play-store/google-play-store-${{ needs.build.outputs.apk_version_uri }}-release/)\n\n  ## Diff (unpacked APK vs Release)\n  - [Phonesky-${{ needs.build.outputs.apk_version_short }}.diff](https://${{ vars.SCND_MIRROR_ORG_DOMAIN }}/${{ vars.SCND_MIRROR_ORG_NAME }}/${{ github.event.repository.name }}/blob/axp/Phonesky-${{ needs.build.outputs.apk_version_short }}.diff)"
+      filelist: >
+        Phonesky_AXP-OS.apk
+        Phonesky_AXP-OS-signed.apk
